// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACeB11UWzjcMgnvarCMCAGKyrI37mn5IQ',
    appId: '1:714385037352:web:2a9042948d28faf3c37d1d',
    messagingSenderId: '714385037352',
    projectId: 'socialmediaapp-48e7f',
    authDomain: 'socialmediaapp-48e7f.firebaseapp.com',
    storageBucket: 'socialmediaapp-48e7f.firebasestorage.app',
    measurementId: 'G-GLK61M4ND9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9Q-6kb0ZFnpSp0Mq6YqMxJs5vjqToeE',
    appId: '1:714385037352:android:b622a5f290d14912c37d1d',
    messagingSenderId: '714385037352',
    projectId: 'socialmediaapp-48e7f',
    storageBucket: 'socialmediaapp-48e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj2Y9HtAB1SqBYI6s5Qvk7EotXtOTxsLQ',
    appId: '1:714385037352:ios:56bfba8e157b1b68c37d1d',
    messagingSenderId: '714385037352',
    projectId: 'socialmediaapp-48e7f',
    storageBucket: 'socialmediaapp-48e7f.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj2Y9HtAB1SqBYI6s5Qvk7EotXtOTxsLQ',
    appId: '1:714385037352:ios:56bfba8e157b1b68c37d1d',
    messagingSenderId: '714385037352',
    projectId: 'socialmediaapp-48e7f',
    storageBucket: 'socialmediaapp-48e7f.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACeB11UWzjcMgnvarCMCAGKyrI37mn5IQ',
    appId: '1:714385037352:web:f87ef8fdc7d314e1c37d1d',
    messagingSenderId: '714385037352',
    projectId: 'socialmediaapp-48e7f',
    authDomain: 'socialmediaapp-48e7f.firebaseapp.com',
    storageBucket: 'socialmediaapp-48e7f.firebasestorage.app',
    measurementId: 'G-X5825DXYP3',
  );
}
